-- User subscriptions table (created first as it has no dependencies)
create table public.user_subscriptions (
  id uuid not null default gen_random_uuid (),
  email character varying not null,
  name character varying null,
  stripe_customer_id character varying null,
  stripe_price_id character varying null,
  plan_name character varying null,
  has_access boolean null default false,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;

-- Wholesaler table (depends on user_subscriptions)
create table public.wholesaler (
  created_at timestamp with time zone not null default now(),
  first_name text null,
  last_name text null,
  email text not null,
  user_id uuid not null,
  id bigint generated by default as identity not null,
  alias text null,
  email_authorized boolean null,
  constraint wholesaler_pkey primary key (id),
  constraint wholesaler_alias_key unique (alias),
  constraint wholesaler_id_key unique (id),
  constraint wholesaler_user_id_key unique (user_id),
  constraint wholesaler_user_id_fkey foreign KEY (user_id) references user_subscriptions (id)
) TABLESPACE pg_default;

-- Tags table (depends on wholesaler)
create table public.tags (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  wholesaler_id bigint null,
  api_id text not null,
  constraint tags_pkey primary key (id),
  constraint tags_api_id_key unique (api_id),
  constraint tags_wholesaler_id_fkey foreign KEY (wholesaler_id) references wholesaler (id)
) TABLESPACE pg_default;

-- Buyer table (depends on wholesaler)
create table public.buyer (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  first_name text null,
  email text null,
  last_name text null,
  phone_num text null,
  wholesaler_id bigint not null,
  api_id text not null,
  constraint buyer_pkey primary key (id),
  constraint buyer_api_id_key unique (api_id),
  constraint buyer_wholesaler_id_fkey foreign KEY (wholesaler_id) references wholesaler (id)
) TABLESPACE pg_default;

-- Buyer_tags junction table (depends on both buyer and tags)
create table public.buyer_tags (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  buyer_id bigint not null,
  tag_id bigint not null,
  constraint buyer_tags_pkey primary key (id),
  constraint buyer_tags_tag_id_fkey foreign KEY (tag_id) references tags (id) on delete CASCADE,
  constraint fk_buyer_tags_on_buyer_delete foreign KEY (buyer_id) references buyer (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.usage (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  wholesaler_id bigint not null,
  subscription_id uuid not null,
  current_plan character varying null,
  buyer_count bigint null,
  tag_count bigint null,
  email_count bigint null,
  constraint usage_pkey primary key (id),
  constraint usage_wholesaler_id_key unique (wholesaler_id),
  constraint usage_subscription_id_fkey foreign KEY (subscription_id) references user_subscriptions (id) on update CASCADE,
  constraint usage_wholesaler_id_fk foreign KEY (wholesaler_id) references wholesaler (id) on update CASCADE
) TABLESPACE pg_default;

-- Enable RLS policies if needed
-- ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.wholesaler ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.buyer ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.buyer_tags ENABLE ROW LEVEL SECURITY;

